#!/usr/bin/env node
// Writes the controlled experiment's results into a module the page imports.
// The calculation itself is pure and testable in src/experiment/evidence.ts;
// this file is deliberately only the filesystem boundary.
//
//   mise exec -- node scripts/snapshot.ts

import { writeFileSync } from "node:fs";
import { buildEvidenceSnapshot } from "../src/experiment/evidence.ts";

const payload = buildEvidenceSnapshot();

writeFileSync(
  "src/experiment/result.generated.ts",
  `// GENERATED by scripts/snapshot.ts — do not edit by hand.
// Regenerate with: mise exec -- node scripts/snapshot.ts
// spec/evidence.test.ts recomputes this entire payload and fails if it is stale.
export const EXPERIMENT = ${JSON.stringify(payload, null, 2)} as const;
`,
  "utf8",
);

function seedReport(seeds: typeof payload.target.seeds): string {
  return (
    `${seeds.usable}/${seeds.attempted} usable: mean ${seeds.meanPercent}%, ` +
    `sd ${seeds.sdPercent}%, usable sign held ${seeds.signHeld}; ` +
    `${seeds.excluded} excluded, attempted sign held ${seeds.attemptedSignHeld}`
  );
}

console.log(
  `✓ src/experiment/result.generated.ts\n` +
    `  target  ${payload.target.closedSeconds}s → ${payload.target.openSeconds}s  ` +
    `${payload.target.deltaPercent >= 0 ? "+" : ""}${payload.target.deltaPercent}%  ` +
    `(${seedReport(payload.target.seeds)})\n` +
    `  control ${payload.control.closedSeconds}s → ${payload.control.openSeconds}s  ` +
    `${payload.control.deltaPercent >= 0 ? "+" : ""}${payload.control.deltaPercent}%  ` +
    `(${seedReport(payload.control.seeds)})`,
);
